language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.8.0"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - cd src
 - mono .nuget/NuGet.exe Restore Rebus.Transports.Redis.sln
 - xbuild /p:configuration=Release
 - .ci/nunit.sh Rebus.Transports.Redis/bin/Release/Rebus.Transports.Redis.dll
 - mono .nuget/NuGet.exe Pack Rebus.Transports.Redis.nuspec

