language: c

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync
  - mv -f src/.nuget/NuGet.mono.targets src/.nuget/NuGet.targets
  - chmod +x lib/xunit/xunit.console.clr4.x86.exe
  - export EnableNuGetPackageRestore=true

script:
  - cd src/
  - xbuild /p:Configuration=Release Rebus.Transports.Redis.sln
  - mono ../lib/xunit/xunit.console.clr4.x86.exe Rebus.Transports.Redis.Tests/bin/Release/Rebus.Transports.Redis.Tests.dll